[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ne_loader = ["py.typed"]

[project]
name = "ne-loader"
version = "0.5"
description = "A simple loader for Natural Earth map data."
authors = [
    { name = "Eric Tunn", email = "erictunn@icloud.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
    "geopandas>=0.12",
    "platformdirs>=4",
    "requests>=2.25",
    "click>=8.4",
]

[project.urls]
Homepage = "https://github.com/erictunn/ne-loader"

[project.scripts]
ne-loader = "ne_loader.cli:main"

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pytest>=9.1.1",
]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "D",
    "F",
    "UP",
    "C4",
    "PTH",
    "I",
    "B",
    "SIM",
]
[tool.pyright]
typeCheckingMode = "strict"
